import React, { useState } from 'react';

const filters = ['All', 'Product Imagery', 'Moodboards', 'Studio Shoots', 'AI Canvas'];
const images = Array.from({ length: 18 }, (_, i) => ({
  id: i,
  src: `https://picsum.photos/seed/${i + 10}/600/800`,
  alt: `Community generated visual ${i + 1}`,
  type: filters[(i % 4) + 1]
}));

const ExplorePage: React.FC = () => {
    const [activeFilter, setActiveFilter] = useState('All');
    const [selectedImage, setSelectedImage] = useState<string | null>(null);

    const filteredImages = activeFilter === 'All' 
        ? images 
        : images.filter(img => img.type === activeFilter);

    return (
        <div className="py-20 sm:py-24 animate-pageFadeIn">
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                <div className="text-center">
                    <h1 className="text-4xl sm:text-5xl font-bold tracking-tight">Creative Inspirations</h1>
                    <p className="mt-4 max-w-2xl mx-auto text-lg text-gray-400">
                        A visual gallery of visuals generated by our community and with our tools.
                    </p>
                </div>

                <div className="flex justify-center flex-wrap gap-2 sm:gap-4 my-12">
                    {filters.map(filter => (
                        <button
                            key={filter}
                            onClick={() => setActiveFilter(filter)}
                            className={`px-4 py-2 text-sm sm:text-base rounded-full transition-colors font-medium ${
                                activeFilter === filter
                                ? 'bg-nutshel-blue text-black'
                                : 'bg-nutshel-gray hover:bg-white/10 text-gray-300'
                            }`}
                        >
                            {filter}
                        </button>
                    ))}
                </div>

                <div className="columns-2 md:columns-3 lg:columns-4 gap-4 space-y-4">
                    {filteredImages.map(image => (
                        <div key={image.id} className="break-inside-avoid cursor-pointer group" onClick={() => setSelectedImage(image.src)}>
                            <div className="overflow-hidden rounded-lg">
                                <img src={image.src} alt={image.alt} className="w-full h-auto transition-transform duration-300 group-hover:scale-105" />
                            </div>
                        </div>
                    ))}
                </div>
            </div>

            {selectedImage && (
                <div 
                    className="fixed inset-0 bg-black/80 backdrop-blur-sm z-50 flex items-center justify-center"
                    onClick={() => setSelectedImage(null)}
                >
                    <img src={selectedImage} alt="Selected visual" className="max-w-[90vw] max-h-[90vh] rounded-lg shadow-2xl" />
                </div>
            )}
        </div>
    );
};

export default ExplorePage;